"""Load the per-patch payload spec (packet type ids, byte transforms, map constants) and the
per-packet content specs generated by tools/re/specgen.py (`specs/<patch>/packet_<type>.json`)."""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Mapping, Optional, Tuple

SPEC_DIR = Path(__file__).resolve().parent.parent / "specs"


@dataclass(frozen=True)
class PayloadSpec:
    patch: str
    waypoint_type: int
    blob_sub: int
    blob_xor: int
    blob_add: int
    map_center: Tuple[float, float]
    packets: Mapping[str, int] = field(default_factory=dict)

    def tbyte(self, b: int) -> int:
        return ((((self.blob_sub - b) & 0xFF) ^ self.blob_xor) + self.blob_add) & 0xFF

    def packet_type(self, role: str) -> Optional[int]:
        """Packet type id playing `role` ("kill", "shop", "cast") in this patch, if its spec is shipped."""
        t = self.packets.get(role)
        return t if t is not None and load_packet_spec(self.patch, t) is not None else None

    def packet_spec(self, role: str) -> Optional[dict]:
        t = self.packets.get(role)
        return load_packet_spec(self.patch, t) if t is not None else None


@lru_cache(maxsize=None)
def load_spec(patch: str) -> Optional[PayloadSpec]:
    path = SPEC_DIR / f"{patch}.json"
    if not path.is_file():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    t = data["blob_transform"]
    packets = {str(k): int(v) for k, v in data.get("packets", {}).items()}
    return PayloadSpec(patch=data["patch"], waypoint_type=int(data["waypoint_type"]),
                       blob_sub=int(t["sub"]), blob_xor=int(t["xor"]), blob_add=int(t["add"]),
                       map_center=tuple(float(x) for x in data["map_center"]), packets=packets)


@lru_cache(maxsize=None)
def load_packet_spec(patch: str, ptype: int) -> Optional[dict]:
    path = SPEC_DIR / patch / f"packet_{ptype}.json"
    if not path.is_file():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def available_patches() -> Tuple[str, ...]:
    return tuple(sorted(p.stem for p in SPEC_DIR.glob("*.json")))
